---
title: Quotes
---

### Fredrik Backman
> Ove had never been asked how he lived before he met her. But if anyone had asked him, he would have answered that he didn’t.

> She just smiled, said that she loved books more than anything, and started telling him excitedly what each of the ones in her lap was about. And Ove realised that he wanted to hear her talking about the things she loved for the rest of his life.

### Osamu Dazai
> To wait. In our lives we know joy, anger, sorrow, and a hundred other emotions, but these emotions all together occupy a bare one per cent of our time. The remaining ninety-nine per cent is just living in waiting. I wait in momentary expectation, feeling as though my breasts are being crushed, for the sound in the corridor of the footsteps of happiness. Empty. Oh, life is too painful, the reality that confirms the universal belief that it is best not to be born.

> As long as you love me, all I want is to spend my whole life by your side.

### F. Scott Fitzgerald
> There are only the pursued, the pursuing, the busy and the tired.

> Let us learn to show our friendship for a man when he is alive and not after he is dead.

### Kazuo Ishiguro
> There was surely nothing to indicate at the time that such evidently small incidents would render whole dreams forever irredeemable.

### Sarah Kane
> There's not a drug on earth can make life meaningful.

### Haruki Murakami
> Still, being able to feel pain was good, he thought. It's when you can't even feel pain anymore that you're in real trouble.

> It is not that the meaning cannot be explained. But there are certain meanings that are lost forever the moment they are explained in words.

> If I had remained at home, I would have spent my life waiting for you to get in touch. And a life spent waiting would mean I couldn't think of anything other than you. Of course, I wouldn't mind. Since you were what I wanted in this world, more than anything.

> We each have a special something we can get only at a special time of our life. Like a small flame. A careful, fortunate few cherish that flame, nurture it, hold it as a torch to light their way. But once that flame goes out, it's gone forever.

### George Orwell
> In the face of pain there are no heroes.

### Ann Patchett
> He was in love, and never had he felt such kindness towards another person. Never had he received such kindness. Maybe the private life wasn't forever. Maybe everyone got it for a little while and then spend the rest of their lives remembering.

> Only a few of us are going to be willing to break our own hearts by trading in the living beauty of imagination for the stark disappointment of words.

### J. D. Salinger
> Many, many men have been just as troubled morally and spiritually as you are right now. Happily, some of them kept records of their troubles. You'll learn from them—if you want to. Just as someday, if you have something to offer, someone will learn something from you. It's a beautiful reciprocal arrangement. And it isn't education. It's history. It's poetry. I'm not trying to tell you that only educated and scholarly men are able to contribute something valuable to the world. It's not so. But I do say that educated and scholarly men, if they're brilliant and creative to begin with—which, unfortunately, is rarely the case—tend to leave infinitely more valuable records behind them than men do who are merely brilliant and creative. They tend to express themselves more clearly, and they usually have a passion for following their thoughts through to the end.

> "Anyway, I like it now," I said. "I mean right now. Sitting here with you and just chewing the fat and horsing—"\
> "That isn't anything really!"\
> "It is so something really! Certainly it is! Why the hell isn't it? People never think anything is anything really. I'm getting goddam sick of it."

### 時雨沢 恵一
> 結局他人の痛みなんて分かってしまえば、まともに生きていけなかったんだ。

### 大友克洋
> 思い出は逃げ込む場所じゃない。