---
title: "ASM 2025"
date: "2025-11-10" 
bibliography: ../references.bib
---

This short informal post is long overdue, but I’ll excuse myself since this website wasn’t up and running in June, when I attended the conference—and besides, I’ve been busy with other things.

I had the chance to attend ASM 2025 in LA back in June. I presented my findings along with my lab partner, and overall I’d say it was a pretty good experience.

Before this, my lab partner and I had attended a smaller research conference in January. That conference was made up mainly of undergraduates. Many disciplines from the biological sciences were represented—everything from ecology to biochemistry. Since we were all undergrads, I found it easier to walk up to posters and ask as many questions as I wanted to satisfy my curiosity, because it was mutually understood that none of us really knew much about each other’s disciplines. It was nice in this way; you could pull the “I’m ignorant just like you, help me out” card, even though any basic lack of knowledge is really my own fault.

Regardless, no one was really in a higher academic caste than you, and you could explore each other’s projects as fellow undergrads and come up with questions to ask—questions that would puzzle both parties in which we’d go home after the conference and try to answer them.

I enjoyed the undergrad conference quite a bit, which is probably a testament to how little I know about my own field, given that I wasn’t bored. But in my defense, most of the students who attended were genuinely interested in what they did (above average, I’d say) and were more than happy to explain their findings.

But back to ASM 2025, the main subject of this post, which took place five months after the undergrad conference. ASM is made up of graduate students but mainly PhDs, so going into it I thought I’d feel a crippling sense of academic inferiority—which was somewhat true, but not the whole story.

It is most definitely true—without exception, or any further consideration—that I know absolutely nothing in comparison to the majority of people that attended the conference. The sheer amount of knowledge some of them possessed astonished me. We had a few people visit our poster, including some who had been part of Dr. Yep’s lab during her fellowship days, who asked the most pointed questions, as if they had been part of the project all along. I recognize the level of devotion, curiosity, and gratification it takes to know so much about a single subject. It amazed me to imagine an entire conference full of people like this. Naturally, I found it difficult to ask the questions I was harboring, afraid I’d be condemned over my ignorance.

I guess what I'm trying to say is this: imagine being the only person in the world who possesses a particular piece of knowledge—something you yourself discovered. You’d be the sole expert in that niche. To be number one in something so hyperspecific, with everyone flocking to you for your insight, is absolutely insane to me.

I’m not the brightest (I'm at the very least, bright enough to know that), and places like this make you realize that. I’m not planning on a career in academia, but I suspect I’ll run into people like this wherever I go. I admire that quality, and seeing people like that encourages me to obsess more over the pursuit of knowledge, even though I’m still very far from it. And I suppose the prospect of possessing vast amounts of knowledge gives me a nice feeling.