---
title: "LB, ∆fur, and Stationary Phase"
date: "2025-10-03" 
categories: 
    - "Lit Review"
bibliography: ../references.bib
---

Dr. Yep noticed how _∆fur_ stalled earlier than the other strains. It’s not necessarily a problem, but I’d like to understand the cause. The paper should also explain this, so we’ll need the rationale anyway.

_∆fur_ entered stationary phase early in Lysogeny Broth (LB). This didn’t happen with any of the other strains or media. _Why_? I’ll attempt to explain this in a few ways.

# ROS Damage
Since this phenomenon was absent in all other media, I think the early stalling most likely reflects a specific interaction between the high intracellular iron characteristic of _∆fur_, and some inherent property of LB.

There appears to be commercial variance in background ROS in LB. LB (Sigma) tends to have more H<sub>2</sub>O<sub>2</sub> than LB (Difco), which is generally gentler (I’m fairly confident we use Sigma). Together with constitutively elevated intracellular iron (Fenton reaction), _∆fur_ may also be exposed to higher levels of peroxide, causing ROS damage. Components such as riboflavin, reducing sugars, and transition metal ions—present in LB—can generate ROS depending on storage conditions, especially with light exposure [@ezratyCommercialLysogenyBroth2014].

Note that _∆fur_ is easily pushed into oxidative stress as well. Deletion of _fur_ indirectly represses _sodB_, which encodes iron superoxide dismutase. This enzyme acts as an antioxidant, preventing ROS damage. But in _∆fur_, this antioxidant is repressed. Cells must then rely on the product of _sodA_ (manganese superoxide dismutase), and, unfortunately, if Mn is lacking in the environment, there isn’t much the cell can do to prevent ROS damage [@chareyreBacterialIronHomeostasis2018].

Side note: although it wasn’t exactly stationary phase, there was some growth inhibition with _∆fur_ in swarming medium as well. Both LB and swarming medium contain yeast extract, which may include components necessary for ROS generation. Of course, this perceived symmetry may be coincidental, and some other intrinsic characteristic attributable to the mutation may be at play; I’m only speculating.

# pH Threshold
The effect seen in _∆fur_ is most likely due to various reasons in combination, including pH damage. One other thing I suspect is the pH threshold of _E. coli_ since LB isn't really buffered, so left alone, growth can take the media up to a pH of 9 without glucose (swarming media has glucose, which may be why CFT doesn't top out in swarming media.) Excretion of excess ammonia is to blame for the alkalinization [@sezonovEscherichiaColiPhysiology2007].

# Carbon Exhaustion
This one is pretty simple. Since LB is pretty limited terms of its nutrient content, lack of carbon sources in combination with the preceding reasons may account for the early stalling observed for _∆fur_ in LB [@sezonovEscherichiaColiPhysiology2007].