---
title: "Mol/Micro Biology is Merely an Abstraction"
date: "2025-08-29" 
categories: 
    - "Misc"
---

I've had this thought for a while but have never bothered writing it down. I was reminded of it while I was writing about sequencing. I found myself making wishy-washy explanations, characteristic of a biologist, when it came to the mechanisms at the molecular level.

I can only explain these pieces of technology from the perspective of an amateur biologist, and would, instead, if possible, explain these technologies from the perspective of a chemist or physicist. But I am merely a biologist. It is my firm belief that after a certain point, biology is merely an abstraction of chemistry and physics, and a thorough understanding of these disciplines (which I do not possess) is required for a complete understanding. That is, my knowledge of these technologies will start breaking down after questions pertaining to the chemistry and physics of these technologies are brought forth. I would argue that one must be a decent physicist and chemist before even attempting to call themselves a good biologist.

The beauty of biology is only appreciated when you understand mechanism in totality.

If a biologist desires to go beyond conventional uses of a tool available to them, an understanding of how things work is crucial, and not just how to use them. But the understanding of _how things work_ only arrives along with the knowledge of these superior disciplines that have generated the field we now call biology.

Since the amount of knowledge required to complete these novel experiments is far beyond the scope of a single biologist, one would expect to find biologists eager to collaborate with chemists and physicists alike. This is not uncommon, but far less common than I expect it to be, which I find very odd.

I apologize for the abrupt ending but I'll stop there since further discussion will turn into a lengthy rant.