---
title: "Entertainment and Loneliness"
date: "2026-01-16" 
categories: 
    - "Misc"
---

In the past, negative things were in excess: disease and its kin. As time progresses, I realize we’re moving toward a society with an excess of positive things: convenience and stimulation. That is, most fortunate individuals living in the modern world are born with a different set of burdens than before. I admit that these burdens are engendered by privilege, but they are choices that decide the course of our short lives; hence, I use the word “burden.” We—the fortunate—are born into this world with far more choices to make, with possibilities stretching into infinity, possibilities that wouldn’t have existed even a few years ago. These so-called burdens involve navigating a world where society is plagued by an obesity of information, entertainment, stimulation, and the like.

I realize there are a plethora of articles, essays, and papers concerning the consequences of the increasingly convenient world, but I’ll try to steer away from these trite topics in this essay. This essay, as the title suggests, will be my exposition on the scarcity of silence, the nature of modern entertainment, and its implications on intimacy. At this point, I must confess that as someone experiencing this world in real time, I have no right to point fingers or criticize others who make the mistakes I describe, since most of these thoughts are experiential—and, I realize, this is quite revealing of my indulgent nature, as you will come to find. Regardless, in organizing my thoughts on the matter, I should find comfort in a society of epistemic chaos. I begin this essay with my thoughts on the nature of modern entertainment.

Entertainment in most modern forms exerts itself upon you, rather than the other way around. For example, with most forms of digital entertainment, one does not need to think so much in order to derive enjoyment. In this way, we find the media doing most of the work of contributing to our enjoyment; it requires less cognitive investment. On the other hand, with forms of media like books—or really, reading in general—we must exert ourselves to derive any kind of enjoyment, making these forms of media much more taxing. The former requires a mere nominal amount of thought, while the latter encourages it.

The disparity in the amount of exertion involved between these forms makes the more difficult forms (books and such) quite unappealing. Why would one ever spend the time or effort these activities require when the nearest screen is inches away—literally at the fingertips? Entertainment has become far too entertaining, with corporations successfully condensing information into as little time as possible, appealing to the most indulgent, selfish parts of ourselves; beautiful faces, vivid images, stupid slapstick humor, and catchy music all garner attention in the most crude yet tragically successful ways. In a true egotistic manner, I’d like to think that I’m above these things, but really, these are things I am unfortunately interested in.

This condensation or simplification of information is evident in almost all imaginable facets of modern stimulation. Pop music (my guilty pleasure), as a genre, for instance, employs catchy but predictable chord progressions and incorporates music videos (of no particular artistic value). Lyrics make less and less sense, focusing on the empty aesthetics and melodically attractive aspects rather than the underlying artistic hues that grant the art form its true value. As I say, this is evident not just in the music industry, but also as time progresses, I’m observing the regression of such measures in all sectors of entertainment.

TV is too easy: condense a twenty-four-minute episode into six by speeding it up fourfold. Scrolling is too cheap: kill thirty minutes by fixing one’s eyes on a screen inches away from one's face and occasionally move one's thumb ever so slightly.

This ridiculously convenient form of escape yields itself to the unwilling mind, yet also leads to forgetting the joys and the fruits of profound duration. And it is precisely because of these cheap forms of entertainment that individuals gradually lose the power to resist these temptations—temptations that started with “I want” but slowly evolved into the malignant “I need,” contributing to a positive feedback loop.

The constant desire for stimulation, I believe, has resulted in the scarcity of silence. In solitude, there is no question about it, but I feel far too many people also find silence in the company of others unbearable, even in situations and relationships not attributable to social awkwardness. This is, fortunately, something I do not understand; I enjoy the quiet far too much. It’s such a shame that people say meaningless, trivial things for the sake of making noise, or conforming, or whatever the reason may be.

But I digress. Entertainment, I believe, is not an inherently depraved thing. In the right forms, I feel it is capable of communicating what it feels like to be in someone’s mind, to convey emotion, and to derive belonging in a very meaningful way. Books—and fiction in particular—grant one the ability to experience another human’s reality in ways that generate perforations in what demarcates our own mind from the rest of the world. With this, our perceptions of what we consider the self become a little more malleable and forgiving. I’m not sure if that makes sense, but I’m afraid it’s the best I can do for now.

I confess my love for books because I desire that intimacy: the feeling of being inside someone else, something I can only find in good literature (I’m careful to say “I,” as I’m not sure others feel this way). _If only I could slice open my chest and stitch together the tubes of our warm blood—share the things that course inside of us._

But in this perpetually accelerating world, I find the possibility of this ever so slim. On the screen, people become dispensable, cheap artifacts of a mere facade. People don’t care as much as before (I really hope they did then) and it’s only apprehension that seizes me as I’m swallowed into the temporal rivers of inevitable dissolution.