---
title: "Ethical Considerations: Sham Surgeries"
date: "2026-03-02"
categories:
    - "Medicine"
bibliography: ../references.bib
---

Sham surgeries are procedures that mimic real surgeries but do not include the critical therapeutic component. They are often used in clinical trials to serve as one of the controls, allowing researchers to assess efficacy of surgical interventions. These surgeries imply that patients undergo anesthesia and incisions, but the actual surgical procedure is not performed. This obviously raises very interesting questions about the ethical implications of such practices.

I'm still an undergrad and most definitely not a medical practitioner (yet), so I have no right to make claims on the technical aspects of medicine. But I can certainly reason about the ethical implications of such practices, given that I read enough about it. Besides, one should never judge an argument based on the authority of the person making it (though this is very tempting), but rather on the strength of the argument itself.

# Utilitarian Arguments in Favor of Sham Surgeries: My Objections to Abbasi and Cifu's Paper
Most of the arguments in favor of sham surgeries employ utilitarian reasoning, which is the idea that the best action is the one that maximizes overall happiness or well-being of a population in question. In this case, the argument is that sham surgeries provide more of a benefit to society than they do harm to the individual patients who undergo them. This is what [@abbasiWhyPatientsBenefit2024] argues. As a evidence-based thinker, I like most of the things Dr. Cifu says, but this is an interesting paper to say the least...

First of all, though the concept of utilitarianism is intuitive and quite clean, it is not without major flaws. It does not take long for one to realize that it can be used to justify all sorts of unethical actions, and there are all sorts of philosophical arguments against it. For example, it can be used to justify sacrificing the rights of a minority group if it benefits the majority. It can also be used to justify actions that are morally wrong, such as torture, if it is believed that it will lead to a greater overall good. Such and such... Very flawed, but very popular because of its simplicity and intuitive appeal. Thus, the paper starts off on the wrong foot.

The paper then goes on to state the following:

> While the sham procedure does not provide any therapeutic benefit, it can benefit a patient by protecting them from undergoing the complete intervention being studied, which may be much more harmful than the sham.

From what I understand, their argument seems to be akin to the following: _let me sock you in the face because it's much better than the stabbing you_. I could very well misinterpreting the passage, but if this is what they are trying to say, then I have a very hard time understanding how they can justify such a claim. It seems to me that they are trying to justify causing harm to an individual by claiming that it is better than causing even more harm. I just don't understand their argument.

The paper defines utility as the "net benefit to a patient", using Quality-Adjusted Life Year as their metric. This is a very flawed metric; it does not take into account the subjective experience of the patient. It also does not account for the fact that different patients may have different values and preferences. For instance, some patients may value their quality of life more than their length of life, and vice versa. I really don't know how you could possibly quantify such a human experience with a single metric. It seems to me that they are trying to reduce a complex human experience to a single number—which is just not possible—in order for the utilitarian argument to work. 

Using this metric, they do a bunch of calculations to show that sham surgeries can provide a net benefit to patients. As I say, utilitarianism is a very flawed ethical framework, and I have no reason to believe that their calculations are at all meaningful. Even if their calculations were accurate, it would not necessarily mean that sham surgeries are ethically justifiable. It would just mean that they provide a net benefit according to their flawed metric.

**Sham surgeries definitely make for better science, but I don't see how they can be ethically justified, especially when employed for riskier procedures. I understand that they can provide a net benefit to society, but I don't see how they can be justified at the expense of the individual patient.**

From what I've read, all the arguments favoring sham surgeries use this kind of faulty logic.

# Arguments Opposing Sham Surgeries
Setting aside all the practicalities of trials emplying sham procedures (blinding, etc); with less invasive procedures, I could see this working, but with more invasive procedures, it becomes much more problematic. The risks of harm to the patient increase significantly, and the ethical justification becomes much harder to defend. The principle of "primum non nocere" (do no harm) is a cornerstone of medical ethics, and sham surgeries can easily violate this principle when they involve significant risk or discomfort to the patient.

As I say, with riskier prodecures like sham neurosurgeries in Parkinson’s disease [@dekkersShamNeurosurgeryPatients2001], even with consent, if I was a provider, I feel I have the moral obligation to explicitly ask: can I drill a hole in your head with no direct therapeutic prospects? 

No one is going to say: _Yeah, of course! Be my guest!_ People are generally agreeable but not to that extent (I hope).

Yet I realize that the absence of sham controls would only result in the perpetuation of ineffective treatments, which is also a harm to patients. It's a difficult question to answer and I find myself within this quagmire where one must do unethical things for an ethical cause. I'm afraid there might not be a better way to conduct sound clinical trials.

To do good science, I'd like to see some sort of agreement between these two considerations: costs of the individual and greater good the population, but as we have seen, this is a very difficult balance to strike. I don't have a clear answer to this question, but I do know that we need to be very careful when considering the ethical implications of sham surgeries.